[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Alex Bates <hi@imalex.xyz>"]
edition = "2018"

[dependencies]
recap = "0.1.1"
serde = "1.0.117"
thiserror = "1.0.22"
yansi = "0.5.0"
regex = "1.4.2"